import { getGeminiClient } from "./gemini";

interface GenerateFaceInput {
  fullDescription: string;
  name: string;
  gender: string;
}

/**
 * Generates a face portrait image using Gemini 2.5 Flash Image model.
 * Returns a Buffer of the generated image (PNG/JPEG).
 */
export async function generateFaceImage(
  input: GenerateFaceInput,
): Promise<{ buffer: Buffer; mimeType: string }> {
  const ai = getGeminiClient();

  const prompt = `Ultra-realistic close-up face reference photograph for a fashion model identity card. Shot on Canon EOS R5 with 105mm macro f/2.8 lens. This is a FACE-ONLY reference photo used to maintain facial identity consistency across multiple photoshoots.

Subject: ${input.name}, ${input.gender} fashion model.
Physical appearance: ${input.fullDescription}

FRAMING — FACE ONLY:
- Tight crop: from forehead hairline to chin, ear to ear
- Face fills 90% of the frame — this is a face reference, not a portrait
- Perfectly frontal angle, symmetrical face position
- Neutral expression with mouth closed, relaxed jaw — like a passport photo but beautiful
- Eyes looking straight into the lens

ULTRA-REALISTIC FACE DETAIL — every facial feature must be hyper-detailed:
- Skin: visible individual pores on nose, cheeks and forehead. Natural skin texture with subtle micro-wrinkles around eyes and mouth. Fine vellus hair (peach fuzz) visible on cheeks and jawline catching the light. Natural skin imperfections — tiny moles, subtle freckles, minor blemishes. Realistic subsurface scattering showing warm tones under thin skin areas (nose, ears, eyelids)
- Eyes: ultra-detailed iris with visible radial fibers, crypts and collarette ring. Natural catchlight from a ring light reflected in both eyes. Individual eyelashes of varying lengths and thickness, some crossing over each other. Subtle red micro-veins in the sclera corners. Natural moisture reflection on the eyeball surface. Visible waterline and tear duct detail
- Eyebrows: individual hairs visible with natural growth direction, varying thickness, some stray hairs outside the main shape
- Lips: fine vertical lip lines (lip wrinkles), natural moisture sheen, realistic color gradient from center to edges, visible cupid's bow definition, slight natural asymmetry
- Nose: visible pore texture especially on nose tip and sides, natural sebaceous filaments, subtle shadow in nostrils, realistic nose bridge highlight
- Ears (partially visible): fine cartilage detail, natural skin tone variation, visible fine hair
- Hairline: natural irregular hairline with baby hairs, individual strands visible at the forehead edge, realistic hair density transition

LIGHTING — clean and even for reference:
- Flat beauty lighting: large ring light or butterfly lighting setup directly in front
- Even illumination across entire face — minimal shadows to show all facial features clearly
- Subtle fill light eliminating under-chin and under-nose shadows
- No dramatic shadows, no moody lighting — this is a reference photo

TECHNICAL:
- Pure white background (#FFFFFF)
- Zero makeup or very minimal no-makeup makeup look — must look like natural bare skin
- Hair pulled back or naturally framing the face but not covering any facial features
- Sharp focus across entire face plane — f/8 deep focus, no bokeh
- ISO 100, zero noise, maximum detail
- Color-accurate white balance, neutral color grading

CRITICAL: This must be INDISTINGUISHABLE from a real photograph of a real human face. Do NOT generate illustration, 3D render, AI-looking smooth skin, plastic-looking eyes, or any stylized look. The face must have natural human asymmetry and imperfections. No text, watermarks, or logos.`;

  const response = await ai.models.generateContentStream({
    model: "gemini-2.5-flash-image",
    config: {
      responseModalities: ["IMAGE", "TEXT"],
    },
    contents: [{ role: "user", parts: [{ text: prompt }] }],
  });

  for await (const chunk of response) {
    if (!chunk.candidates?.[0]?.content?.parts) continue;

    const part = chunk.candidates[0].content.parts[0];
    if (part.inlineData) {
      const buffer = Buffer.from(part.inlineData.data || "", "base64");
      const mimeType = part.inlineData.mimeType || "image/png";
      return { buffer, mimeType };
    }
  }

  throw new Error("No image was generated by the AI model");
}
